// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ACF.Infrastructure.Data
{
    public partial class ACFContext : DbContext
    {
        public ACFContext()
        {
        }

        public ACFContext(DbContextOptions<ACFContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Clientes>(entity =>
            {
                //entity.HasNoKey();
                entity.HasKey(e => e.Identificación);
                entity.Property(e => e.Edad).HasColumnName("edad");

                entity.Property(e => e.FechaDeCreación)
                    .HasColumnType("datetime")
                    .HasColumnName("fechaDeCreación")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Identificación).ValueGeneratedOnAdd();

                entity.Property(e => e.PrimerApellido)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("primerApellido")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.PrimerNombre)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("primerNombre")
                    .HasDefaultValueSql("('')");
            });

            modelBuilder.Entity<Usuarios>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Contraseña)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("contraseña");

                entity.Property(e => e.IdUsuario)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("idUsuario");

                entity.Property(e => e.NombreUsuario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombreUsuario");

                entity.Property(e => e.TipoUsuario).HasColumnName("tipoUsuario");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}