// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Models.Models;

namespace ACF.Infrastructure.Data
{
    public partial class ACFContext : DbContext
    {
        public ACFContext()
        {
        }

        public ACFContext(DbContextOptions<ACFContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Clientes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Edad).HasColumnName("edad");

                entity.Property(e => e.FechaDeCreación)
                    .HasColumnType("datetime")
                    .HasColumnName("fechaDeCreación")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Identificación).ValueGeneratedOnAdd();

                entity.Property(e => e.PrimerApellido)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("primerApellido")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.PrimerNombre)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("primerNombre")
                    .HasDefaultValueSql("('')");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}