// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Core.Entities
{
    public partial class Clientes
    {
        [Key]
        public int Identificación { get; set; }
        public string PrimerNombre { get; set; }
        public string PrimerApellido { get; set; }
        public int Edad { get; set; }
        public DateTime? FechaDeCreación { get; set; }
    }
}